/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'class',
    content: [
      "./index.html",
      "./src/**/*.{js,ts,jsx,tsx}",
      "./content/**/*.md",
    ],
    theme: {
      extend: {
        colors: {
          primary: {
            50: "#f1f5f9",
            100: "#e2e8f0",
            200: "#cbd5e1",
            300: "#94a3b8",
            400: "#64748b",
            500: "#334155",
            600: "#1e293b",
            700: "#172554",
            800: "#0f172a",
            900: "#0b1322"
          },
          secondary: {
            50: "#f0fdfa",
            100: "#ccfbf1",
            200: "#99f6e4",
            300: "#5eead4",
            400: "#2dd4bf",
            500: "#14b8a6",
            600: "#0d9488",
            700: "#0f766e",
            800: "#115e59",
            900: "#134e4a"
          },
          success: {
            50: "#f0fdf4",
            100: "#dcfce7",
            200: "#bbf7d0",
            300: "#86efac",
            400: "#4ade80",
            500: "#22c55e",
            600: "#16a34a",
            700: "#15803d",
            800: "#166534",
            900: "#14532d"
          },
          warning: {
            50: "#fffbeb",
            100: "#fef3c7",
            200: "#fde68a",
            300: "#fcd34d",
            400: "#fbbf24",
            500: "#f59e0b",
            600: "#d97706",
            700: "#b45309",
            800: "#92400e",
            900: "#78350f"
          },
          error: {
            50: "#fef2f2",
            100: "#fee2e2",
            200: "#fecaca",
            300: "#fca5a5",
            400: "#f87171",
            500: "#ef4444",
            600: "#dc2626",
            700: "#b91c1c",
            800: "#991b1b",
            900: "#7f1d1d"
          },
          surface: {
            50: "#f8fafc",
            100: "#f1f5f9",
            200: "#e2e8f0",
            300: "#cbd5e1",
            400: "#94a3b8",
            500: "#64748b",
            600: "#475569",
            700: "#334155",
            800: "#1f2937",
            900: "#111827",
            base: 'var(--surface-base)',
            raised: 'var(--surface-raised)',
            sunken: 'var(--surface-sunken)',
            overlay: 'var(--surface-overlay)',
          },
          tx: {
            primary: 'var(--text-primary)',
            secondary: 'var(--text-secondary)',
            tertiary: 'var(--text-tertiary)',
            muted: 'var(--text-muted)',
          },
          ln: {
            DEFAULT: 'var(--border-default)',
            subtle: 'var(--border-subtle)',
            strong: 'var(--border-strong)',
          },
          accent: {
            DEFAULT: 'var(--accent)',
            hover: 'var(--accent-hover)',
            subtle: 'var(--accent-subtle)',
            text: 'var(--accent-text)',
          },
          interactive: {
            bg: 'var(--interactive-bg)',
            hover: 'var(--interactive-hover)',
            border: 'var(--interactive-border)',
            text: 'var(--interactive-text)',
          },
          danger: {
            DEFAULT: 'var(--danger)',
            hover: 'var(--danger-hover)',
            subtle: 'var(--danger-subtle)',
            text: 'var(--danger-text)',
          },
          input: {
            bg: 'var(--input-bg)',
            border: 'var(--input-border)',
            text: 'var(--input-text)',
            placeholder: 'var(--input-placeholder)',
          },
          status: {
            'pass-bg': 'var(--status-pass-bg)',
            'pass-text': 'var(--status-pass-text)',
            'pass-border': 'var(--status-pass-border)',
            'fail-bg': 'var(--status-fail-bg)',
            'fail-text': 'var(--status-fail-text)',
            'fail-border': 'var(--status-fail-border)',
            'hold-bg': 'var(--status-hold-bg)',
            'hold-text': 'var(--status-hold-text)',
            'hold-border': 'var(--status-hold-border)',
            'pending-bg': 'var(--status-pending-bg)',
            'pending-text': 'var(--status-pending-text)',
            'pending-border': 'var(--status-pending-border)',
          },
        }
      },
    },
    plugins: [],
  }
